/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS GAMING PC
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Volum = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        Volume = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Tab1.setToolTipText("Balok");

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 40, 150, 16);
        jPanel2.add(Sisi);
        Sisi.setBounds(30, 70, 140, 30);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 80, 41, 16);

        Volum.setText("Volume");
        Volum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumActionPerformed(evt);
            }
        });
        jPanel2.add(Volum);
        Volum.setBounds(30, 130, 75, 25);

        Tab1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Masukkan Panjang jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 30, 210, 16);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(80, 70, 48, 30);
        jPanel3.add(r);
        r.setBounds(10, 70, 70, 30);

        Volume.setText("Volume");
        Volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeActionPerformed(evt);
            }
        });
        jPanel3.add(Volume);
        Volume.setBounds(20, 120, 75, 25);

        Tab1.addTab("Bola", jPanel3);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Panjang : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 130, 16);

        jLabel3.setText("Masukkan Lebar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 120, 16);

        jLabel4.setText("Masukkan Tinggi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 120, 16);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 130, 17, 20);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 80, 17, 16);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 30, 17, 16);
        jPanel1.add(Panjang);
        Panjang.setBounds(160, 20, 120, 30);

        Lebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebarActionPerformed(evt);
            }
        });
        jPanel1.add(Lebar);
        Lebar.setBounds(160, 70, 120, 30);

        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        jPanel1.add(Tinggi);
        Tinggi.setBounds(160, 120, 120, 30);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(150, 190, 69, 25);

        Tab1.addTab("Balok", jPanel1);

        getContentPane().add(Tab1);
        Tab1.setBounds(0, 60, 400, 390);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(61, 20, 280, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void LebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LebarActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        try{
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        int hasil = panjang*lebar*tinggi;
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil, "Luas", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : ", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void VolumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumActionPerformed
        try{
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
            JOptionPane.showMessageDialog(null,"Luas permukaan Kubus Adalah : "+hasil, "Luas", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : ", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumActionPerformed

    private void VolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeActionPerformed
        try{
        float jari;
        jari = Integer.parseInt(r.getText());
        float hasil = (float)(4/3*3.14*jari*jari*jari);
            JOptionPane.showMessageDialog(null,"Luas permukaan Bola Adalah : "+hasil, "Luas", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : ", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_VolumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTabbedPane Tab1;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton Volum;
    private javax.swing.JButton Volume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField r;
    // End of variables declaration//GEN-END:variables
}
