/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS GAMING PC
 */
public class ujikebolehan extends javax.swing.JFrame {

    /**
     * Creates new form ujikebolehan
     */
    public ujikebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        BB = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        Coba = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        try {
            jLabel11 =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "GUI.ujikebolehan_jLabel11");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 190, 22);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 60, 16);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 60, 16);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 80, 16);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 220, 80, 20);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(140, 70, 180, 30);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(140, 120, 60, 30);
        getContentPane().add(BB);
        BB.setBounds(140, 170, 60, 30);

        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });
        getContentPane().add(output);
        output.setBounds(20, 450, 360, 30);

        saran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saranActionPerformed(evt);
            }
        });
        getContentPane().add(saran);
        saran.setBounds(20, 500, 360, 30);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(60, 290, 69, 25);

        Coba.setText("Coba lagi");
        Coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobaActionPerformed(evt);
            }
        });
        getContentPane().add(Coba);
        Coba.setBounds(160, 290, 90, 25);

        exit.setText("Keluar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(280, 290, 69, 25);

        rdb1.setText("Perempuan");
        getContentPane().add(rdb1);
        rdb1.setBounds(140, 220, 93, 25);

        rdb2.setText("Laki - laki");
        getContentPane().add(rdb2);
        rdb2.setBounds(260, 220, 83, 25);

        jLabel6.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 360, 190, 16);

        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 410, 160, 16);
        getContentPane().add(Ideal);
        Ideal.setBounds(250, 360, 30, 22);

        jLabel8.setText("Kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 360, 14, 20);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 130, 17, 16);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 180, 13, 16);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 400, 580);

        setBounds(0, 0, 418, 624);
    }// </editor-fold>//GEN-END:initComponents

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    private void saranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saranActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        try{
        int tinggi = Integer.parseInt(Tinggi.getText());
        int berat = Integer.parseInt(BB.getText());
        String nama = Nama.getText();
        int ideal = 0;
        if(rdb1.isSelected()){
            ideal = tinggi - 100;
        }else if(rdb2.isSelected()){
            ideal = tinggi - 104;
        }
        String temp = Integer.toString(ideal);
        if(ideal < berat){
            Ideal.setText(temp);
            output.setText("Maaf "+nama + ", sepertinya anda Overweight :(");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
        }else if(ideal > berat){
            Ideal.setText(temp);
            output.setText("Maaf "+nama+" , sepertinya anda Underweight :(");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }else{
            Ideal.setText(temp);
            output.setText("Hallo "+nama+" , Berat badan anda sudah ideal :)");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat:)");
        }
        }catch(Exception a){
            JOptionPane.showMessageDialog(null, "Kotak input belum terisi semua", "Message", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_HitungActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void CobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobaActionPerformed
        Tinggi.setText("");
        BB.setText("");
        Nama.setText("");
        Ideal.setText("");
        rdb1.setSelected(false);
        rdb2.setSelected(false);
        output.setText("");
        saran.setText("");
    }//GEN-LAST:event_CobaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ujikebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BB;
    private javax.swing.JButton Coba;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Ideal;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField output;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables
}
