/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan;

/**
 *
 * @author ASUS GAMING PC
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Proses = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        HB1 = new javax.swing.JTextField();
        HB2 = new javax.swing.JTextField();
        HB3 = new javax.swing.JTextField();
        HB4 = new javax.swing.JTextField();
        Diskon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 130, 22);

        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 47, 100, 16);

        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 76, 89, 16);

        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(62, 105, 89, 16);

        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(62, 134, 89, 16);

        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(62, 163, 70, 16);

        Proses.setBackground(new java.awt.Color(255, 255, 51));
        Proses.setText("Proses");
        Proses.setToolTipText("");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(60, 200, 71, 25);

        Hapus.setBackground(new java.awt.Color(255, 255, 51));
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(170, 200, 67, 25);

        Exit.setBackground(new java.awt.Color(255, 255, 51));
        Exit.setText("Keluar");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(280, 200, 69, 25);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 340, 160);
        getContentPane().add(HB1);
        HB1.setBounds(180, 40, 120, 22);
        getContentPane().add(HB2);
        HB2.setBounds(180, 70, 120, 22);
        getContentPane().add(HB3);
        HB3.setBounds(180, 100, 120, 22);
        getContentPane().add(HB4);
        HB4.setBounds(180, 130, 120, 22);

        Diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiskonActionPerformed(evt);
            }
        });
        getContentPane().add(Diskon);
        Diskon.setBounds(180, 160, 120, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        HB1.setText("");
        HB2.setText("");
        HB3.setText("");
        HB4.setText("");
        Diskon.setText("");
        TA.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        int hb1 = Integer.parseInt(HB1.getText());
        int hb2 = Integer.parseInt(HB2.getText());
        int hb3 = Integer.parseInt(HB3.getText());
        int hb4 = Integer.parseInt(HB4.getText());
        int diskon = Integer.parseInt(Diskon.getText());
        
        int totalharga = hb1+hb2+hb3+hb4;
        int totalharga1 = totalharga;
        int totalbayar;
        totalbayar = totalharga*diskon/100;
        totalharga1 = totalharga - totalbayar;
        totalbayar = totalharga1;
        TA.setText("Harga barang 1 : "+hb1+"\nHarga barang 2 : "+hb2+"\nHarga barang 3 : "+hb3+"\nHarga barang 4 : "+hb4+"\nDiskon anda : "+diskon+"%"+"\nTotal Harga : "+totalharga+"\nTotal Bayar : "+totalbayar);
    }//GEN-LAST:event_ProsesActionPerformed

    private void DiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField HB1;
    private javax.swing.JTextField HB2;
    private javax.swing.JTextField HB3;
    private javax.swing.JTextField HB4;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Proses;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
